### PR TITLE
Issue 28: Improvements & fixes

### LINKED ISSUE #28: Miscellaneous Improvements and Fixes
1) StatCards: 
- use grid instead of flexbox, 
- improve responsiveness (lg: 3 columns, md: 2 columns, otherwise 1) 
- add green/red indication whether the portfolio is in profit or loss 
- add icons to the cards

2) Navigation
- add navigation to xs, sm screens
- fix navigation on md screens

3) Portfolio Performance Chart
- add custom hook to prepare chart data
- extract chart component into smaller ones 

4) Loading state component 
- make a loading state component that will be reused across app to handle loading state 

5) Unify colors across app

6) Fix Pie Chart 
- modify usePieChartData hook to calculate portfolio share based on latest price data (not purchase price)
- improve responsiveness - add legend for small screens, otherwise use labels

### PR DESCRIPTION
**Pull request by tmuzikova**
1. StatCards:
- use grid instead of flexbox,
- improve responsiveness (lg: 3 columns, md: 2 columns, otherwise 1)
- add green/red indication whether the portfolio is in profit or loss
- add icons to the cards

2. Navigation
- add navigation to xs, sm screens
- fix navigation on md screens

3. Portfolio Performance Chart
- add custom hook to prepare chart data
- extract chart component into smaller ones

4. Loading state component
- make a loading state component that will be reused across app to handle loading state

5. Unify colors across app (use colors defined in index.css)

6. Fix Pie Chart
- modify usePieChartData hook to calculate portfolio share based on current price data (not purchase price)
- improve responsiveness - add legend for small screens, otherwise use labels

### CODE REVIEW

File: src/app/Layout/AppSidebar.tsx [hunk 1]
```diff
@@ -42,10 +47,17 @@ export const AppSidebar = () => {
...
 
+  const triggerIcon = isMobile && openMobile ? <XIcon /> : <PanelLeftIcon />;
+
   return (
-    <Sidebar collapsible="icon">
+    <Sidebar
+      collapsible="icon"
+      side={isMobile ? 'right' : 'left'}
+      variant="sidebar"
+    >
```
Comment (matyasmihalka) [inline src/app/Layout/AppSidebar.tsx]: I would advise to refactor the sidebar logic. Ideally there should be a separate sidebar component for mobile and desktop version. In that way it would be easier to understand how it's cusntructed.

File: src/components/ui/sidebar.tsx [hunk 2]
```diff
@@ -204,14 +206,22 @@ const Sidebar = React.forwardRef<
...
             }
             side={side}
           >
+            <DialogDescription>
+              <VisuallyHidden>
+                Use the navigation links to browse the app.
+              </VisuallyHidden>
+            </DialogDescription>
+            <DialogTitle>
+              <VisuallyHidden>Sidebar Navigation</VisuallyHidden>
```
Comment (matyasmihalka) [inline src/components/ui/sidebar.tsx]: Are these visually hidden elements needed for anything? It the purpose is accessibility they should be in czech

File: src/features/dashboard/components/PieChartCard.tsx [hunk 3]
```diff
@@ -61,17 +69,42 @@ export const PieChartCard = () => {
       <CardContent className="flex pb-2">
         <ChartContainer
           config={chartConfig}
-          className="max-h-[450px] w-full [&_.recharts-pie-label-text]:fill-muted-foreground [&_.recharts-pie-label-text]:text-sm [&_.recharts-pie-label-text]:font-medium"
+          className={`w-full [&_.recharts-pie-label-text]:fill-muted-foreground [&_.recharts-pie-label-text]:text-sm [&_.recharts-pie-label-text]:font-medium ${
+            isLargeScreen ? 'h-[450px]' : 'h-[350px]'
+          }`}
         >
-          <PieChart>
+          <PieChart margin={{ bottom: !isLargeScreen ? 20 : 0 }}>
```
Comment (matyasmihalka) [inline src/features/dashboard/components/PieChartCard.tsx]: In this case also it would be better create separate pie chart components for large screen and small screen, then you don't have to check the condition in a couple of places.
I would expect something like:
```tsx
{ isLargeScreen ? <LargePie /> : <SmallPie /> }
```

File: src/features/dashboard/components/PortfolioHistoryChart.tsx [hunk 4]
```diff
@@ -1,115 +1,163 @@
...
+            .charAt(0)
+            .toUpperCase() +
+          date
+            .toLocaleDateString('cs-CZ', { month: 'short' })
+            .replace('.', '')
+            .slice(1)
+        );
+      default:
+        return `${date.getDate()}.${date.getMonth() + 1}.`;
+    }
```
Comment (matyasmihalka) [inline src/features/dashboard/components/PortfolioHistoryChart.tsx]: These switch statements are generally not used very often in frontend development. Usually they can be replaced with an object map that's easier to understand.

The above can be replaced with:
```ts
// Somewhere outside of the component
const formatMonth = (date: Date): string => {
  const month = date
    .toLocaleDateString('cs-CZ', { month: 'short' })
    .replace('.', '');
  return month.charAt(0).toUpperCase() + month.slice(1);
};


const timeRangeMap: Record<string, (date: Date) => string> = {
      'Za celou dobu': (date) => date.getFullYear().toString(),
      '1R': (date) => formatMonth(date),
      YTD: (date) => formatMonth(date),
    };

return timeRangeMap[selectedTimeRange](date);
```

File: src/features/dashboard/components/PortfolioHistoryChart.tsx [hunk 5]
```diff
@@ -1,115 +1,163 @@
...
+  };
+
+  const getXAxisProps = () => {
+    switch (selectedTimeRange) {
```
Comment (matyasmihalka) [inline src/features/dashboard/components/PortfolioHistoryChart.tsx]: The same goes for this switch statement, an object map would be a better solution

File: src/features/dashboard/components/StatCards.tsx [hunk 6]
```diff
@@ -1,102 +1,160 @@
...
+      valueColor: isPositive
+        ? 'text-[hsl(var(--chart-2))]'
+        : 'text-destructive',
+    };
+  };
+
+  const unrealizedProfitStyle = getProfitColorAndIcon(
+    statData.unrealizedProfit,
+  );
+  const realizedProfitStyle = getProfitColorAndIcon(statData.realizedProfit);
```
Comment (matyasmihalka) [inline src/features/dashboard/components/StatCards.tsx]: Icon and color style should be separately calculated. If you need to use "and" in any given naming it's a good indicator that it should be split. In this case it could be:
```tsx
  const getProfitIcon = (value: number) =>
  value >= 0 ? (
    <TrendingUp className="h-5 w-5 text-[hsl(var(--chart-2))]" />
  ) : (
    <TrendingDown className="h-5 w-5 text-destructive" />
  );

  const profitStyle = (value: number) =>
  value >= 0 ? 'text-[hsl(var(--chart-2))]' : 'text-destructive';

  const UnrealizedProfitIcon = getProfitIcon(statData.unrealizedProfit);
  const RealizedProfitIcon = getProfitIcon(statData.realizedProfit);

  const unrealizedColorStyle = profitStyle(statData.unrealizedProfit);
  const realizedProfitStyle = profitStyle(statData.realizedProfit);
```

File: src/hooks/usePortflioPerformanceData/utils/calculateDailyPortfolioValue.ts [hunk 7]
```diff
@@ -0,0 +1,49 @@
...
+import { DailyPortfolio } from '../../../utils/portfolioCalculations/getDailyPortfolio';
+import { CurrentPortfolioItem } from '@/types/currentPortfolio';
+import { getLatestAvailablePrices } from './getLatestAvailablePrice';
+import { getApplicablePrice } from './getApplicablePrice';
+
+export const calculateDailyPortfolioValues = (
+  dailyPortfolio: DailyPortfolio,
+  stockPrices: HistoricalPriceData[],
+): { date: string; portfolio_value: number }[] => {
+  let lastAvailablePrices = getLatestAvailablePrices(stockPrices);
```
Comment (matyasmihalka) [inline src/hooks/usePortflioPerformanceData/utils/calculateDailyPortfolioValue.ts]: This function is hard to understand, ideally it should be deconstructed to smaller functions and more deterministic steps. You use `let` keywords for two different variables that makes it much harder to follow what exactly is happening. 
Do you think you can come up with a refactored version of this function that will be easier to understand.

File: src/hooks/usePortflioPerformanceData/utils/getApplicablePrice.ts [hunk 8]
```diff
@@ -0,0 +1,28 @@
+import { HistoricalPriceData } from '@/types/historicalPrices';
+import { FX_RATE } from '@/utils/portfolioCalculations/const/FX_RATE';
+
+export const getApplicablePrice = (
+  symbolPriceData: HistoricalPriceData | undefined,
+  date: string,
+  lastAvailablePrices: Record<string, number>,
+): number | undefined => {
+  if (!symbolPriceData) return undefined;
```
Comment (matyasmihalka) [inline src/hooks/usePortflioPerformanceData/utils/getApplicablePrice.ts]: This condition can be avoided if you don't even call this function when `symbolPriceData` is `undefined`.

File: src/hooks/usePortflioPerformanceData/utils/getLatestAvailablePrice.ts [hunk 9]
```diff
@@ -0,0 +1,16 @@
...
+export const getLatestAvailablePrices = (
+  stockPrices: HistoricalPriceData[],
+): Record<string, number> => {
+  const prices: Record<string, number> = {};
+
+  stockPrices.forEach((stock) => {
+    if (stock.historical.length > 0) {
+      prices[stock.symbol] = stock.historical[0].close * FX_RATE;
+    }
+  });
```
Comment (matyasmihalka) [inline src/hooks/usePortflioPerformanceData/utils/getLatestAvailablePrice.ts]: Reduce would be better to use here. Generally, most of the time `forEach` can be replaced with reduce.

File: src/utils/portfolioCalculations/calculateInvestedAmount.ts [hunk 10]
```diff
@@ -1,6 +1,25 @@
...
+  }, 0);
+
+  const investedAmount = {
+    withFees: totalInvestedAmountWithFees,
+    noFees: totalInvestedAmountNoFees,
+  };
+
+  return investedAmount;
+};
+
```
Comment (matyasmihalka) [inline src/utils/portfolioCalculations/calculateInvestedAmount.ts]: Just small cosmetic suggestions. Number of characters could be reduced how to write this function and in the same time maintain it's readability. Less characters = less things to read = easier to understand. Of course, this is not this simple, finding the right balance will come with experience. 
```ts
export const calculateCurrentInvestedAmount = (
  currentPortfolio: CurrentPortfolioItem[],
) => {
  const totalInvestedAmountWithFees = currentPortfolio.reduce(
    (sum, tx) => sum + (tx.value.total + (tx.totalFees || 0)) * FX_RATE,
    0,
  );
  const totalInvestedAmountNoFees = currentPortfolio.reduce(
    (sum, tx) => sum + tx.value.total * FX_RATE,
    0,
  );

  return {
    withFees: totalInvestedAmountWithFees,
    noFees: totalInvestedAmountNoFees,
  };
};
```

File: src/components/ui/sidebar.tsx (hunk 2 above)
Comment (tmuzikova) [reply src/components/ui/sidebar.tsx]: Yes, I was getting accessibility errors without them. I translated them to czech.

**Review by matyasmihalka — DISMISSED** [review]

**Review by matyasmihalka — APPROVED** [review]
